### ISSUE TITLE
Mistake in correlation-function

### ISSUE THREAD

**Issue by pjuergens** [EducationalTestingService/factor_analyzer#108]
**Describe the bug**
The function `corr(x)` doesn't return the correlation matrix. For the dataframe I am using with 40 rows/observations and 73 columns/variables (which unfortunately I cannot publish here) and no nan-values the diagonal elements of the computed correlation matrix are 0.975 instead of 1. Using the pandas `df.corr()` leads to the correct result.

It seems to me that the degrees of freedom in calculating the covariance matrix (`r = cov(x)`) is falsely set to 0 and should be 1 instead, i.e. `r = cov(x, ddof=1)`.

By the way: In this case with more variables than observations `calculate_kmo` fails and returns nan which I guess makes sence. However returning a message in the underlaying `partial_correlations`-function would be very helpful.

**Comment by desilinguist** [comment]
@pjuergens would it be possible for you to create a minimal example that illustrates the issue so we can use it as a test?

**Comment by jbiggsets** [comment]
Working on this issue. This is actually a disconnect between numpy and pandas, since they calculate the standard deviation differently (numpy with `ddof=0` as the default).

If we pass a numpy array to this `corr()` function, we get the correct correlation matrix, but that's not the case with a DataFrame, so we'll have to check to see which type of object is being passed and set `ddof` accordingly or just use `np.std(x, ddof=1)` in both cases?

![image](https://user-images.githubusercontent.com/30508716/188507398-d2ec61df-4d5f-462f-9a52-2379b34f3aa6.png)
