### ISSUE TITLE
Possibility to choose the correlation 

### ISSUE THREAD

**Issue by mariaolaaksonen** [EducationalTestingService/factor_analyzer#15]
Would it be possible to give the factor analysis a parameter where you would define the correlation to be used in the correlation matrix calculation? At least pandas corr() function has three methods (Pearson, Spearman and Kendall) from which to choose from.

**Comment by desilinguist** [comment]
That’s a great idea! 👍

**Comment by jbiggsets** [comment]
Yes, absolutely. 

We will address this in the next release. It would probably be best to allow users to optionally pass their own correlation matrix directly to the `analyze()` method, rather than just passing an argument to `df.corr()`. So, if a user wants something different, like the tetrachoric correlation matrix for dichotomous data, they can just calculate it themselves.

Thanks very much for raising this as an issue!

**Comment by jbiggsets** [comment]
I've merged this into the `master` branch. It will be included in the next release. Thanks again for the suggestion, @mariaolaaksonen!
