### ISSUE TITLE
Results not the same as in R psych package.

### ISSUE THREAD

**Issue by yetong2023** [EducationalTestingService/factor_analyzer#32]
The testing data is:

x1 | x2 | x3 | x4 | x5
-- | -- | -- | -- | --
0.2 | 3 | 21.5 | 13.6 | 7.3
0.5 | 8.4 | 33.5 | 12.1 | 9.8
1.3 | 13.6 | 49.4 | 13.6 | 5.2
1.3 | 11.6 | 47.5 | 13 | 4.9
2.4 | 17.7 | 45.2 | 12.5 | 3.4
0.5 | 12.7 | 50.3 | 10.1 | 5.1

In Python:

```
from factor_analyzer import FactorAnalyzer
fa=FactorAnalyzer()
fa.analyze(data,2,rotation='varimax')
fa.loadings
```
Then I got:
       Factor1   Factor2
x1    0.958472  0.288052
x2    0.943449 -0.311609
x3    0.747067 -0.520007
x4   -0.016515  0.720617
x5   -0.791465  0.072079

In R:
```
b= read_excel("b.xlsx")
fa=principal(b,2,rotate='varimax')
fa$loadings#查看载荷矩阵
```
However, I got:
Loadings:
     RC1    RC2   
x1    0.917  0.261
x2    0.941 -0.247
x3    0.802 -0.460
x4           0.974
x5   -0.885

**Comment by jbiggsets** [comment]
Hi @binbinliao,

I think the issue here is that you're using the principal factor extraction method from `psych`. The `factor_analyzer` package allows you to use either a minimum residual or maximum likelihood method, but not principal factor extraction.

The `psych` package's `fa()` function uses a minimum residual extraction method by default. When I check the loadings matrix using this function, here are the results:

```
import pandas as pd
from factor_analyzer import FactorAnalyzer

df = pd.read_csv('data.csv')
fa = FactorAnalyzer()
fa.analyze(df, 2, rotation='varimax')
fa.loadings
```
||Factor1 | Factor2
|--|-- | --
|x1 | 0.958472 | 0.288052
|x2 |0.943449 | -0.311609
|x3| 0.747067 | -0.520007
|x4|-0.016515 | 0.720617
|x5|-0.791465 | 0.072079

```
library(psych)

df <- read.csv('data.csv')
fac <- fa(cov(df), nfactors=2, rotate='varimax')
fac$loadings
```
||MR1 | MR2
|--|-- | --
|x1 | 0.959 | 0.288
|x2 | 0.944 | -0.313
|x3| 0.747 | -0.521
|x4|           | 0.719
|x5|-0.791   | 

Please let me know if you have any other questions, or if I can close this issue. We are actually planning to incorporate principal factor analysis soon, most likely in our next release.

**Comment by yetong2023** [comment]
Thanks a lot. It's my bad that I missed PCA in psych. Factor_analyzer is a great FA package for Python!

**Comment by IlanReinstein** [comment]
Hi, 
I have encountered a similar behavior with my data:

Python:
`from factor_analyzer import FactorAnalyzer`
`fa = FactorAnalyzer(n_factors=1)`
`fa.fit(zX)`

The result for the loadings:

`
array([[-0.74235256],
       [-0.69099752],
       [-0.74306825],
       [-0.78354219],
       [-0.66765199],
       [-0.67873326]])
`

For R instead, with the same data:

`X_fa <- psych::fa(zX, nfactors = 1, rotate = 'varimax')`
`X_fa$loadings`

The loadings are:

MR1  
0.742
0.691
0.743
0.784
0.668
0.679

They are the same values but with opposite signs. The Python package warns about using any rotation for a single factor (R package does not). Is this related to that? I ensured I am using the same method (default minres) for estimation. 

The data cannot be made public at this moment but I am attaching the correlation matrix to give a bit more context as to why I'm considering using FA in the first place.

I appreciate any insight into why this may be happening.

**Comment by jbiggsets** [comment]
Hello, can you try setting the rotation in `FactorAnalyzer` to `varimax`? The default is `'promax'`.

```
fa = FactorAnalyzer(n_factors=1, rotation='varimax')
fa.fit(zX)
```

If you are still noticing a discrepancy, can you share the correlation matrix? I didn't see it attached to this issue. (There may still be a discrepancy with R, but I want to verify that this is the case.)

**Comment by IlanReinstein** [comment]
I still see the same issue when changing to `varimax`; the loadings have the same value but with a negative sign.

Sorry about the correlation matrix, here it is:

[correlation_matrix_factor_analysis.csv](https://github.com/EducationalTestingService/factor_analyzer/files/6591889/correlation_matrix_factor_analysis.csv)
