### ISSUE TITLE
Something wrong about "rotation_matrix_"

### ISSUE THREAD

**Issue by p09323028** [EducationalTestingService/factor_analyzer#78]
**Describe the bug**
There are different signs in "Component Transform Matrix" between SPSS and this package.

**Screenshots**
https://imgur.com/7TJ4Flr

**Comment by jbiggsets** [comment]
Can you provide some additional details, so that we can try to replicate?

It would be most helpful if you could provide:
1. A snippet of your `factor_analyzer` code, so that we can see the method and type of rotation you're doing.
2. A snippet of your SPSS code.
3. If possible, the dataset that you're using.

It's hard to look into this issue without having the above information. Thank you!

**Comment by p09323028** [comment]
Provide all information here:
https://tinyurl.com/2c3c9hej

This is my course homework,
but I got different results with my classmates'.

Thanks.

**Comment by desilinguist** [comment]
Addressed by #79.
