### ISSUE TITLE
Methods to derive loadings

### ISSUE THREAD

**Issue by duckykao** [EducationalTestingService/factor_analyzer#82]
Hi, Thanks a lot for providing such package in Factor Analysis.

I am a student working on multivariate analysis class, and I have learned three methods in deriving out loading matrix.
1. Principal component method (ref : https://aaronschlegel.me/factor-analysis-principal-component-method-r.html)
2. Principal factor method  (ref : https://rpubs.com/aaronsc32/factor-analysis-principal-factor-method)
3. Maximum likelihood method 

I can see that the method 'ml' corresponds to maximum likelihood method, and from the source code I guess 'principal' method corresponds to Principal component method (please correct me if I am wrong). However, I cannot tell which method corresponds to Principal factor method, please let me know if possible.

Thanks a lot.

**Comment by jbiggsets** [comment]
Hello, @duckykao . Thanks very much. The `principal` method in `factor_analyzer` actually corresponds to the principal factor method, _not_ principal component analysis. If you want to do PCA, you can use `scikit-learn`.

Let me know if that doesn't make sense, or if you have additional questions. Otherwise, I will close this issue.

**Comment by duckykao** [comment]
Hi, @jbiggsets Thanks a lot for explaining, there is no more questions. Really appreciate it.
